In [1]:
# Cell 1: Import all necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Display settings for better viewing
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

print("✅ Libraries imported successfully")

Matplotlib is building the font cache; this may take a moment.

✅ Libraries imported successfully

In [4]:
# Cell 2: Load the Netflix dataset
# Make sure your CSV file is in the 'data' folder
df = pd.read_csv('D:/Netflix content strategy analysis/data/raw data/netflix_titles.csv')

# Quick check
print(f"✅ Dataset loaded successfully!")
print(f"📊 Shape: {df.shape[0]} rows × {df.shape[1]} columns")
print(f"\n📋 First 3 rows:")
df.head(3)

✅ Dataset loaded successfully!
📊 Shape: 8807 rows × 12 columns

📋 First 3 rows:

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...

In [5]:
# Cell 3: Check basic info about your data
print("📋 DATA INFORMATION:")
print("-" * 50)
df.info()

📋 DATA INFORMATION:
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [6]:
# Cell 4: Check for missing values
print("🔍 MISSING VALUES COUNT:")
print("-" * 50)
missing_data = df.isnull().sum()
missing_percentage = (df.isnull().sum() / len(df)) * 100

# Create a nice dataframe to view missing data
missing_df = pd.DataFrame({
    'Column': df.columns,
    'Missing_Count': missing_data.values,
    'Missing_Percentage': missing_percentage.values.round(2)
})
print(missing_df[missing_df['Missing_Count'] > 0].sort_values('Missing_Count', ascending=False))

🔍 MISSING VALUES COUNT:
--------------------------------------------------
       Column  Missing_Count  Missing_Percentage
3    director           2634               29.91
5     country            831                9.44
4        cast            825                9.37
6  date_added             10                0.11
8      rating              4                0.05
9    duration              3                0.03

In [7]:
# Cell 5: Check basic statistics of numerical columns
print("📊 BASIC STATISTICS:")
print("-" * 50)
# First, let's see if we have any numeric columns to check
df.describe()

📊 BASIC STATISTICS:
--------------------------------------------------

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [8]:
# Cell 6: Check unique values in key columns
print("🎯 UNIQUE VALUES IN KEY COLUMNS:")
print("-" * 50)

categorical_columns = ['type', 'rating', 'country', 'listed_in']
for col in categorical_columns:
    unique_count = df[col].nunique()
    print(f"{col}: {unique_count} unique values")
    
    # Show top 5 most common values for each
    print(f"Top 5 in {col}:")
    print(df[col].value_counts().head(3))
    print("-" * 30)

🎯 UNIQUE VALUES IN KEY COLUMNS:
--------------------------------------------------
type: 2 unique values
Top 5 in type:
type
Movie      6131
TV Show    2676
Name: count, dtype: int64
------------------------------
rating: 17 unique values
Top 5 in rating:
rating
TV-MA    3207
TV-14    2160
TV-PG     863
Name: count, dtype: int64
------------------------------
country: 748 unique values
Top 5 in country:
country
United States     2818
India              972
United Kingdom     419
Name: count, dtype: int64
------------------------------
listed_in: 514 unique values
Top 5 in listed_in:
listed_in
Dramas, International Movies    362
Documentaries                   359
Stand-Up Comedy                 334
Name: count, dtype: int64
------------------------------

In [9]:
# Cell 7: Create a clean copy of the dataframe
df_clean = df.copy()
print("✅ Created clean copy of dataframe")

✅ Created clean copy of dataframe

In [10]:
# Cell 8: Handle missing values in 'director' column
print("🎬 Handling missing directors...")
# Check current missing count
print(f"Before: {df_clean['director'].isnull().sum()} missing")

# Fill with 'Unknown'
df_clean['director'] = df_clean['director'].fillna('Unknown')

# Verify
print(f"After: {df_clean['director'].isnull().sum()} missing")
print("✅ Director column cleaned")

🎬 Handling missing directors...
Before: 2634 missing
After: 0 missing
✅ Director column cleaned

In [11]:
# Cell 9: Handle missing values in 'cast' column
print("👥 Handling missing cast members...")
print(f"Before: {df_clean['cast'].isnull().sum()} missing")

# Fill with 'Unknown'
df_clean['cast'] = df_clean['cast'].fillna('Unknown')

print(f"After: {df_clean['cast'].isnull().sum()} missing")
print("✅ Cast column cleaned")

👥 Handling missing cast members...
Before: 825 missing
After: 0 missing
✅ Cast column cleaned

In [12]:
# Cell 10: Handle missing values in 'country' column
print("🌍 Handling missing countries...")
print(f"Before: {df_clean['country'].isnull().sum()} missing")

# Let's find the most common country (mode)
most_common_country = df_clean['country'].mode()[0]
print(f"Most common country: {most_common_country}")

# Fill missing with the most common country
df_clean['country'] = df_clean['country'].fillna(most_common_country)

print(f"After: {df_clean['country'].isnull().sum()} missing")
print("✅ Country column cleaned")

🌍 Handling missing countries...
Before: 831 missing
Most common country: United States
After: 0 missing
✅ Country column cleaned

In [13]:
# Cell 11: Handle 'date_added' and 'rating' - these are important for analysis
print("📅 Handling date_added and rating...")

# Check current state
print(f"date_added missing: {df_clean['date_added'].isnull().sum()}")
print(f"rating missing: {df_clean['rating'].isnull().sum()}")

# Remove rows where either is missing (they're crucial for analysis)
initial_rows = len(df_clean)
df_clean = df_clean.dropna(subset=['date_added', 'rating'])
final_rows = len(df_clean)

print(f"Rows removed: {initial_rows - final_rows}")
print(f"Rows remaining: {final_rows}")
print("✅ Cleaned date_added and rating")

📅 Handling date_added and rating...
date_added missing: 10
rating missing: 4
Rows removed: 14
Rows remaining: 8793
✅ Cleaned date_added and rating

In [14]:
# Cell 12: Clean and convert date_added
print("🔄 Converting date_added to datetime format...")

# Check a sample of date_added before cleaning
print("Sample of raw date_added values:")
print(df_clean['date_added'].head())

# Remove any extra spaces
df_clean['date_added'] = df_clean['date_added'].str.strip()

# Convert to datetime
df_clean['date_added'] = pd.to_datetime(df_clean['date_added'])

# Check the result
print("\nAfter conversion:")
print(df_clean['date_added'].head())
print(f"\nDate range: {df_clean['date_added'].min()} to {df_clean['date_added'].max()}")
print("✅ Date column converted successfully")

🔄 Converting date_added to datetime format...
Sample of raw date_added values:
0    September 25, 2021
1    September 24, 2021
2    September 24, 2021
3    September 24, 2021
4    September 24, 2021
Name: date_added, dtype: object

After conversion:
0   2021-09-25
1   2021-09-24
2   2021-09-24
3   2021-09-24
4   2021-09-24
Name: date_added, dtype: datetime64[ns]

Date range: 2008-01-01 00:00:00 to 2021-09-25 00:00:00
✅ Date column converted successfully

In [15]:
# Cell 13: Extract temporal features from date_added
print("📊 Creating temporal features...")

# Extract year, month, quarter
df_clean['year_added'] = df_clean['date_added'].dt.year
df_clean['month_added'] = df_clean['date_added'].dt.month
df_clean['quarter_added'] = df_clean['date_added'].dt.quarter

# Extract day name (Monday, Tuesday, etc.)
df_clean['day_added'] = df_clean['date_added'].dt.day_name()

# Check the new columns
print("New columns created:")
print(df_clean[['date_added', 'year_added', 'month_added', 'quarter_added', 'day_added']].head())
print("✅ Temporal features created")

📊 Creating temporal features...
New columns created:
  date_added  year_added  month_added  quarter_added day_added
0 2021-09-25        2021            9              3  Saturday
1 2021-09-24        2021            9              3    Friday
2 2021-09-24        2021            9              3    Friday
3 2021-09-24        2021            9              3    Friday
4 2021-09-24        2021            9              3    Friday
✅ Temporal features created

In [16]:
# Cell 14: Create decade feature from release_year
print("📅 Creating release decade feature...")

# Create decade (e.g., 1990, 2000, 2010)
df_clean['release_decade'] = (df_clean['release_year'] // 10) * 10

# Check distribution
print("\nContent by decade:")
print(df_clean['release_decade'].value_counts().sort_index())
print("✅ Decade feature created")

📅 Creating release decade feature...

Content by decade:
release_decade
1920       1
1940      15
1950      11
1960      25
1970      70
1980     129
1990     274
2000     807
2010    5916
2020    1545
Name: count, dtype: int64
✅ Decade feature created

In [17]:
# Cell 15: Calculate content age at addition
print("⏱️ Calculating content age at addition...")

# Calculate how old content was when added to Netflix
df_clean['content_age_at_addition'] = df_clean['year_added'] - df_clean['release_year']

# Check some examples
print("Examples of content age:")
example = df_clean[['title', 'release_year', 'year_added', 'content_age_at_addition']].head(10)
print(example)

# Basic statistics
print(f"\nAverage age at addition: {df_clean['content_age_at_addition'].mean():.1f} years")
print(f"Oldest content added: {df_clean['content_age_at_addition'].max()} years old")
print("✅ Content age feature created")

⏱️ Calculating content age at addition...
Examples of content age:
                              title  release_year  year_added  \
0              Dick Johnson Is Dead          2020        2021
1                     Blood & Water          2021        2021
2                         Ganglands          2021        2021
3             Jailbirds New Orleans          2021        2021
4                      Kota Factory          2021        2021
5                     Midnight Mass          2021        2021
6  My Little Pony: A New Generation          2021        2021
7                           Sankofa          1993        2021
8     The Great British Baking Show          2021        2021
9                      The Starling          2021        2021

   content_age_at_addition
0                        1
1                        0
2                        0
3                        0
4                        0
5                        0
6                        0
7                       28
8                        0
9                        0

Average age at addition: 4.7 years
Oldest content added: 93 years old
✅ Content age feature created

In [18]:
# Cell 16: Process 'listed_in' (genres) column
print("🎭 Processing genres column...")

# Count how many genres each title has
df_clean['genre_count'] = df_clean['listed_in'].apply(lambda x: len(str(x).split(',')))

# Show results
print("Genre count distribution:")
print(df_clean['genre_count'].value_counts().sort_index())

# Example of titles with multiple genres
print("\nExample of titles with most genres:")
multi_genre = df_clean.nlargest(5, 'genre_count')[['title', 'listed_in', 'genre_count']]
print(multi_genre)
print("✅ Genre count feature created")

🎭 Processing genres column...
Genre count distribution:
genre_count
1    2015
2    3052
3    3726
Name: count, dtype: int64

Example of titles with most genres:
           title                                          listed_in  \
1  Blood & Water    International TV Shows, TV Dramas, TV Mysteries
2      Ganglands  Crime TV Shows, International TV Shows, TV Act...
4   Kota Factory  International TV Shows, Romantic TV Shows, TV ...
5  Midnight Mass                 TV Dramas, TV Horror, TV Mysteries
7        Sankofa   Dramas, Independent Movies, International Movies

   genre_count
1            3
2            3
4            3
5            3
7            3
✅ Genre count feature created

In [19]:
# Cell 17: Process 'cast' column to count cast members
print("👥 Counting cast members...")

# Function to count cast members safely
def count_cast_members(cast_string):
    if pd.isna(cast_string) or cast_string == 'Unknown':
        return 0
    return len(str(cast_string).split(','))

# Apply the function
df_clean['cast_count'] = df_clean['cast'].apply(count_cast_members)

# Check distribution
print("Cast size distribution:")
print(df_clean['cast_count'].value_counts().sort_index().head(10))

print(f"\nAverage cast size: {df_clean['cast_count'].mean():.1f} members")
print(f"Maximum cast size: {df_clean['cast_count'].max()} members")
print("✅ Cast count feature created")

👥 Counting cast members...
Cast size distribution:
cast_count
0     825
1     879
2     200
3     193
4     272
5     368
6     618
7     615
8    1178
9     687
Name: count, dtype: int64

Average cast size: 7.3 members
Maximum cast size: 50 members
✅ Cast count feature created

In [20]:
# Cell 18: Process duration for Movies
print("🎬 Processing movie durations...")

# Create a column for movie durations in minutes
def extract_movie_duration(duration_string):
    if pd.isna(duration_string):
        return None
    if 'min' in str(duration_string):
        return int(str(duration_string).replace(' min', ''))
    return None

df_clean['duration_minutes'] = df_clean['duration'].apply(extract_movie_duration)

# Check movie durations
movie_durations = df_clean[df_clean['type'] == 'Movie']['duration_minutes'].dropna()
print(f"Movies: {len(movie_durations)} titles with duration info")
print(f"Average movie length: {movie_durations.mean():.0f} minutes")
print(f"Shortest movie: {movie_durations.min()} minutes")
print(f"Longest movie: {movie_durations.max()} minutes")
print("✅ Movie duration feature created")

🎬 Processing movie durations...
Movies: 6126 titles with duration info
Average movie length: 100 minutes
Shortest movie: 3.0 minutes
Longest movie: 312.0 minutes
✅ Movie duration feature created

In [21]:
# Cell 19: Process duration for TV Shows
print("📺 Processing TV show seasons...")

# Create a column for TV show seasons
def extract_tv_seasons(duration_string):
    if pd.isna(duration_string):
        return None
    if 'Season' in str(duration_string):
        # Handle "1 Season" or "2 Seasons"
        return int(str(duration_string).split()[0])
    return None

df_clean['seasons'] = df_clean['duration'].apply(extract_tv_seasons)

# Check TV show seasons
tv_seasons = df_clean[df_clean['type'] == 'TV Show']['seasons'].dropna()
print(f"TV Shows: {len(tv_seasons)} titles with season info")
print(f"Average seasons: {tv_seasons.mean():.1f}")
print(f"Most seasons: {tv_seasons.max()}")
print("✅ TV show seasons feature created")

📺 Processing TV show seasons...
TV Shows: 2664 titles with season info
Average seasons: 1.8
Most seasons: 17.0
✅ TV show seasons feature created

In [22]:
# Cell 20: Extract primary country (first country listed)
print("🌍 Creating primary country feature...")

def extract_primary_country(country_string):
    if pd.isna(country_string) or country_string == 'Unknown':
        return 'Unknown'
    # Take first country if multiple are listed
    return str(country_string).split(',')[0].strip()

df_clean['primary_country'] = df_clean['country'].apply(extract_primary_country)

# Check top primary countries
print("Top 10 primary countries:")
print(df_clean['primary_country'].value_counts().head(10))
print("✅ Primary country feature created")

🌍 Creating primary country feature...
Top 10 primary countries:
primary_country
United States     4034
India             1008
United Kingdom     627
Canada             271
Japan              257
France             212
South Korea        211
Spain              181
Mexico             134
Australia          115
Name: count, dtype: int64
✅ Primary country feature created

In [23]:
# Cell 21: Final check of cleaned data
print("🔍 FINAL DATA QUALITY CHECK")
print("-" * 50)

# Check for any remaining missing values
print("Remaining missing values:")
remaining_missing = df_clean.isnull().sum()
print(remaining_missing[remaining_missing > 0])

# Check new columns created
print("\nNew columns added:")
original_columns = set(df.columns)
new_columns = set(df_clean.columns) - original_columns
for col in sorted(new_columns):
    print(f"  ✅ {col}")

print(f"\nFinal shape: {df_clean.shape[0]} rows × {df_clean.shape[1]} columns")

🔍 FINAL DATA QUALITY CHECK
--------------------------------------------------
Remaining missing values:
duration               3
duration_minutes    2667
seasons             6129
dtype: int64

New columns added:
  ✅ cast_count
  ✅ content_age_at_addition
  ✅ day_added
  ✅ duration_minutes
  ✅ genre_count
  ✅ month_added
  ✅ primary_country
  ✅ quarter_added
  ✅ release_decade
  ✅ seasons
  ✅ year_added

Final shape: 8793 rows × 23 columns

In [24]:
# Cell 22: Save the cleaned dataset
print("💾 Saving cleaned data...")

# Save to CSV
df_clean.to_csv('D:/Netflix content strategy analysis/data/processed data/netflix_clean_data.csv', index=False)
print("✅ Cleaned data saved to 'data/netflix_clean_data.csv'")

# Also save a sample for quick viewing
df_clean.head(10).to_csv('D:/Netflix content strategy analysis/data/sample data/sample_cleaned_data.csv', index=False)
print("✅ Sample data saved to 'data/sample_cleaned_data.csv'")

💾 Saving cleaned data...
✅ Cleaned data saved to 'data/netflix_clean_data.csv'
✅ Sample data saved to 'data/sample_cleaned_data.csv'

In [25]:
# Cell 23: Quick summary statistics of your cleaned data
print("📊 SUMMARY STATISTICS OF CLEANED DATA")
print("-" * 50)

print(f"Total titles: {len(df_clean):,}")
print(f"Movies: {len(df_clean[df_clean['type'] == 'Movie']):,}")
print(f"TV Shows: {len(df_clean[df_clean['type'] == 'TV Show']):,}")
print(f"Date range: {df_clean['year_added'].min()} - {df_clean['year_added'].max()}")
print(f"Countries represented: {df_clean['primary_country'].nunique()}")
print(f"Genres categories: {df_clean['listed_in'].nunique()}")

📊 SUMMARY STATISTICS OF CLEANED DATA
--------------------------------------------------
Total titles: 8,793
Movies: 6,129
TV Shows: 2,664
Date range: 2008 - 2021
Countries represented: 86
Genres categories: 513

In [26]:
# Cell 24: Quick verification
print("🎯 VERIFICATION CHECKLIST")
print("-" * 50)

checks = {
    "No missing in critical columns": df_clean[['director', 'cast', 'country', 'date_added', 'rating']].isnull().sum().sum() == 0,
    "Date column is datetime": pd.api.types.is_datetime64_any_dtype(df_clean['date_added']),
    "Year added column exists": 'year_added' in df_clean.columns,
    "Genre count column exists": 'genre_count' in df_clean.columns,
    "Cast count column exists": 'cast_count' in df_clean.columns,
    "Primary country column exists": 'primary_country' in df_clean.columns
}

for check, passed in checks.items():
    status = "✅ PASSED" if passed else "❌ FAILED"
    print(f"{status} - {check}")

if all(checks.values()):
    print("\n🎉 GREAT! Your data is ready for Phase 3 (EDA)!")
else:
    print("\n⚠️ Some checks failed. Review the failed steps.")

🎯 VERIFICATION CHECKLIST
--------------------------------------------------
✅ PASSED - No missing in critical columns
✅ PASSED - Date column is datetime
✅ PASSED - Year added column exists
✅ PASSED - Genre count column exists
✅ PASSED - Cast count column exists
✅ PASSED - Primary country column exists

🎉 GREAT! Your data is ready for Phase 3 (EDA)!